version: "3"

# define services (containers)
services:
  {{ cookiecutter.project_slug }}_api:
    image: {{ cookiecutter.project_slug }}_api
    command: gunicorn app.main:api --bind 0.0.0.0:5000 -k uvicorn.workers.UvicornWorker
    ports:
      # host:container
      - "{{ cookiecutter.api_port }}:5000"
    restart: always
    environment:
      - MONGODB_SERVERNAME={{ cookiecutter.project_slug }}_db
    depends_on:
      - {{ cookiecutter.project_slug }}_db
    container_name: "{{ cookiecutter.project_slug }}_api"

  {{ cookiecutter.project_slug }}_db:
    image: mongo
    volumes:
      - {{ cookiecutter.mongodb_local_storage }}:/data/db
    container_name: "{{ cookiecutter.project_slug }}_db"
    ports:
      - "{{ cookiecutter.mongodb_port }}:27017"
    restart: always
