version: "3"

# define services (containers)
services:
  {{cookiecutter.api_container_name}}:
    build:
      context: '.'
    image: {{cookiecutter.api_container_name}}
    command: gunicorn app.main:api --bind 0.0.0.0:5000 -w {{cookiecutter.gunicorn_uvicorn_workers}} -k uvicorn.workers.UvicornWorker
    ports:
      # host:container
      - "{{cookiecutter.api_port}}:5000"
    restart: always
    depends_on:
      - {{cookiecutter.mongodb_container_name}}
    container_name: "{{cookiecutter.api_container_name}}"

  {{cookiecutter.mongodb_container_name}}:
    image: mongo
    command:
        - '--auth'
    volumes:
      - {{cookiecutter.mongodb_local_storage}}:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    container_name: "{{cookiecutter.mongodb_container_name}}"
    restart: always